In [1]:
codedir = "/Users/admin/UDel/FASTLab/Summer2021_Research/SESNspectraPCA/code"
imagedir = "/Users/admin/UDel/FASTLab/Summer2021_Research/imagedir"
datadir = ("/Users/admin/Udel/FASTLab/Summer2021_Research/"
           "SESNspectraPCA/Data/DataProducts")

In [2]:
import sys  
sys.path.insert(0, codedir)

In [51]:
import os
import glob

# import sklearn
# from sklearn.svm import LinearSVC
# from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
# import astropy.units as u
# import astropy.constants as c
# from scipy.integrate import trapezoid
# from astropy.convolution import convolve_fft, convolve, Gaussian1DKernel

import SNIDsn
import SNIDdataset as snid
# import SNePCA

# import degrade
# import kernels
# import plotutils
# import utils
# import classify_PCASVC as cps

import astrodash as ad

# from collections import OrderedDict

from importlib import reload

In [8]:
ls ../Data/DataProducts/dataset0.pickle

Fig5/             dataset0.pickle   dataset15.pickle  svm_score_tables/
README.md         dataset10.pickle  dataset5.pickle


In [20]:
dataset0 = snid.loadPickle('../Data/DataProducts/dataset0.pickle')
dataset5 = snid.loadPickle('../Data/DataProducts/dataset5.pickle')
dataset10 = snid.loadPickle('../Data/DataProducts/dataset10.pickle')
dataset15 = snid.loadPickle('../Data/DataProducts/dataset15.pickle')

In [111]:
dataset0["sn1998dt"].header

{'Nspec': 9,
 'Nbins': 1024,
 'WvlStart': 2500.0,
 'WvlEnd': 10000.0,
 'SplineKnots': 11,
 'SN': 'sn1998dt',
 'dm15': -9.99,
 'TypeStr': 'Ib-norm',
 'TypeInt': 2,
 'SubTypeInt': 2}

In [115]:
dataset15["sn1998dt"].phases

array([13.6])

In [89]:
dataset0[list(dataset0.keys())[0]].phases

array([1.8])

In [96]:
for key, value in dataset15.items():
    print(value.header["Nspec"])

3
8
6
9
11
3
24
4
18
5
16
10
12
28
8
9
48
8
16
26
73
12
14
7
7
26
12
11
31
15
8
17
37
8
9
38
27
1
13
22
25
14
19
28
26
34
11
25
26
5
11
2
21
16


In [21]:
SNlist = []
SNlist.extend(snid.getDiagnostics(dataset0)[0])
SNlist.extend(snid.getDiagnostics(dataset5)[0])
SNlist.extend(snid.getDiagnostics(dataset10)[0])
SNlist.extend(snid.getDiagnostics(dataset15)[0])

In [27]:
SNlist = np.array(SNlist)
SNlist.shape, SNlist

((217,),
 array(['sn1998dt', 'sn1999dn', 'sn1999ex', 'sn2004gq', 'sn2005bf',
        'sn2005hg', 'sn2007ag', 'sn2007C', 'sn2007kj', 'sn2007uy',
        'sn2007Y', 'sn2008D', 'sn2009er', 'sn2009jf', 'sn2012P',
        'sn2013df', '16gkg', '11hs', 'sn1993J', 'sn1996cb', 'sn1998fa',
        'sn2000H', 'sn2004ff', 'sn2006el', 'sn2008bo', 'sn2009mg',
        'sn2011dh', 'sn2011ei', 'sn2011fu', 'LSQ14efd', '13ge', '15dtg',
        'sn1994I', 'sn2004aw', 'sn2004fe', 'sn2005az', 'sn2005ek',
        'sn2005kl', 'sn2005mf', 'sn2007gr', 'sn2011bm', 'sn2013dk',
        '16coi', 'sn1997ef', 'sn1998bw', 'sn2002ap', 'sn2003jd',
        'sn2003lw', 'sn2006aj', 'sn2007ru', 'sn2009bb', 'sn2010bh',
        'sn2012ap', 'sn2012bz', 'sn2013dx', 'sn1998dt', 'sn1999dn',
        'sn1999ex', 'sn2005bf', 'sn2006ep', 'sn2007ag', 'sn2007C',
        'sn2007kj', 'sn2007Y', 'sn2008D', 'sn2009er', 'sn2009iz',
        'sn2009jf', 'sn2012P', 'sn2013df', '16gkg', '10as', '11hs',
        'sn1993J', 'sn1996cb', 'sn2000H', 

In [29]:
np.unique(SNlist).shape, np.unique(SNlist)

((73,),
 array(['10as', '11hs', '13ge', '15dtg', '16coi', '16gkg', '17ein',
        'LSQ14efd', 'sn1983N', 'sn1990B', 'sn1990I', 'sn1990U', 'sn1993J',
        'sn1994I', 'sn1996cb', 'sn1997ef', 'sn1998bw', 'sn1998dt',
        'sn1998fa', 'sn1999dn', 'sn1999ex', 'sn2000H', 'sn2002ap',
        'sn2003bg', 'sn2003dh', 'sn2003jd', 'sn2003lw', 'sn2004aw',
        'sn2004dk', 'sn2004fe', 'sn2004ff', 'sn2004ge', 'sn2004gq',
        'sn2004gt', 'sn2004gv', 'sn2005az', 'sn2005bf', 'sn2005ek',
        'sn2005hg', 'sn2005kl', 'sn2005mf', 'sn2006T', 'sn2006aj',
        'sn2006el', 'sn2006ep', 'sn2007C', 'sn2007Y', 'sn2007ag',
        'sn2007bg', 'sn2007gr', 'sn2007kj', 'sn2007ru', 'sn2007uy',
        'sn2008D', 'sn2008ax', 'sn2008bo', 'sn2009bb', 'sn2009er',
        'sn2009iz', 'sn2009jf', 'sn2009mg', 'sn2010ay', 'sn2010bh',
        'sn2011bm', 'sn2011dh', 'sn2011ei', 'sn2011fu', 'sn2012P',
        'sn2012ap', 'sn2012bz', 'sn2013df', 'sn2013dk', 'sn2013dx'],
       dtype='<U8'))

In [74]:
snidsn = SNIDsn.SNIDsn()
snidsn.loadSNIDlnw('/Users/admin/UDel/FASTLab/astrodash/templates/training_set/sn1998dt.lnw')

In [108]:
snidsn.phases

array([ 1.8,  2.8,  5.7,  8.7,  9.7, 12.6, 13.6, 18.5, 33.8])

In [52]:
dash_files = glob.glob("/Users/admin/UDel/FASTLab/"
                       "astrodash/templates/training_set/*lnw")

dash_SNlist = []
for file in dash_files:
    snidsn = SNIDsn.SNIDsn()
    snidsn.loadSNIDlnw(file)
    dash_SNlist.append(snidsn.header["SN"])

In [53]:
len(dash_files)

514

In [54]:
len(dash_SNlist)

514

In [56]:
for SN in np.unique(SNlist):
    print(f"SNID SN {SN}: ", end="")
    if SN in dash_SNlist:
        print("in DASH training set.")
    else:
        print("")

SNID SN 10as: 
SNID SN 11hs: 
SNID SN 13ge: 
SNID SN 15dtg: 
SNID SN 16coi: 
SNID SN 16gkg: 
SNID SN 17ein: 
SNID SN LSQ14efd: 
SNID SN sn1983N: in DASH training set.
SNID SN sn1990B: in DASH training set.
SNID SN sn1990I: in DASH training set.
SNID SN sn1990U: in DASH training set.
SNID SN sn1993J: in DASH training set.
SNID SN sn1994I: in DASH training set.
SNID SN sn1996cb: in DASH training set.
SNID SN sn1997ef: in DASH training set.
SNID SN sn1998bw: in DASH training set.
SNID SN sn1998dt: in DASH training set.
SNID SN sn1998fa: in DASH training set.
SNID SN sn1999dn: 
SNID SN sn1999ex: in DASH training set.
SNID SN sn2000H: in DASH training set.
SNID SN sn2002ap: in DASH training set.
SNID SN sn2003bg: in DASH training set.
SNID SN sn2003dh: in DASH training set.
SNID SN sn2003jd: in DASH training set.
SNID SN sn2003lw: in DASH training set.
SNID SN sn2004aw: in DASH training set.
SNID SN sn2004dk: in DASH training set.
SNID SN sn2004fe: in DASH training set.
SNID SN sn2004ff: in